---
title: PCA on input data in JSON
output: 
  html_document:
    self_contained: false
params:
  printcode:
    label: "Display Code"
    value: FALSE
  path:
    label: "Path to JSON file"
    value: "./Data/data_norm.json"
    input: file
  target:
    label: "Name of group variable"
    value: "group"
    input: text
---

```{js, echo=FALSE}
$('.title').css('color', 'red')
```

```{css, echo=FALSE}
body {
  color: red;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$printcode)
```


```{r, include=FALSE}
## Initialization
library("jsonlite")
library("ggbiplot")
library("factoextra")
library("plotly")

# Load data
print(params$path)
json_data <- fromJSON(txt = params$path)
input_df <- json_data$data

# Separate predictor name list and target
predictor_list <- json_data$nameList
# target <- setdiff(names(input_df), predictor_list)
target <- params$target

# apply PCA (Assume no missing values!!!)
input_df.pca <- prcomp(input_df[, predictor_list],
                       center = TRUE,
                       scale. = TRUE)

# Access results
# Extract eigenvalues
eig.val <- get_eigenvalue(input_df.pca)

# Results for Variables (column)
res.var <- get_pca_var(input_df.pca)
res.var$coord          # Coordinates
res.var$contrib        # Contributions to the PCs
res.var$cos2           # Quality of representation

# Results for each individual Record (row)
res.ind <- get_pca_ind(input_df.pca)
res.ind$coord          # Coordinates
res.ind$contrib        # Contributions to the PCs
res.ind$cos2           # Quality of representation
```


## Results {.tabset .tabset-fade}

### Explained Variance

```{r, fig.dim=c(8, 6), out.width="100%"}

# Construct output dataframe
DT::datatable(eig.val)

# Univariate variance
p <- fviz_eig(
  input_df.pca,
  xlab = "PC",
  main = "Variance of each PC",
  addlabels = TRUE,
  barfill = "white",
  barcolor = "darkblue",
  linecolor = "red"
) +
  labs(title = "Variances - PCA",
       x = "Principal Component") +
  theme_minimal()

p
```

### Cumulative Expalined Variance

```{r, fig.dim=c(8, 6)}
# Cumulative variance
p <- ggplot(data=eig.val, aes(x=as.numeric(gsub("^.*\\.","",row.names(eig.val))), y=cumulative.variance.percent), group=1) +
  geom_line(color="red")+
  geom_point()+
  geom_text(aes(label=sprintf("%0.2f%%", round(cumulative.variance.percent, digits = 2))),hjust=0.5, vjust=-0.5) +
  labs(title = "Cumulative % of explained total variance",
       x = "Principal Component",
       y = 'Cumulative Variance (%)') +
  theme_minimal()
p
# ggplotly()
```

### Biplot by PCs
```{r, fig.dim=c(8, 6), out.width="100%"}
# Biplot of first 2 PC
p <- ggbiplot(
  input_df.pca,
  choices = c(1, 2),
  groups = input_df[[target]],
  ellipse = TRUE,
  ellipse.prob = .95
) +
  theme_minimal()

ggplotly()

# Extract results
projected_df <- as.data.frame(input_df.pca$x)
projected_df[target] <- input_df[[target]]

```

### Variable Loadings
```{r}
# Visualiza results
DT::datatable(input_df.pca$rotation)
```

### Projected Records
Data projected to PC. Centered and scaled data multipled by eigenvectors.  
```{r}
# Visualiza results
DT::datatable(projected_df)
```

### Visualization of Projected Records
```{r, fig.align='center', out.width="100%"}
if (dim(input_df.pca$rotation)[2] > 3) {
  # Scale factor for loadings
  scale.loads <- 5
  
  # 3D plot
  p <- plot_ly(data = projected_df,
               x =  ~ PC1,
               y =  ~ PC2,
               z =  ~ PC3) %>%
    add_trace(type = "scatter3d",
              mode = "markers",
              color = projected_df[[target]])
  
  for (k in 1:nrow(input_df.pca$rotation)) {
    x <- c(0, input_df.pca$rotation[k, 1]) * scale.loads
    y <- c(0, input_df.pca$rotation[k, 2]) * scale.loads
    z <- c(0, input_df.pca$rotation[k, 3]) * scale.loads
    p <- p %>% add_trace(
      x = x,
      y = y,
      z = z,
      name = paste0("PC", k),
      type = "scatter3d",
      mode = "lines",
      line = list(width = 8),
      opacity = 1
    )
  }
  p <- p %>% layout(title = "Written Premium and PIF", 
         autosize = TRUE)
  # p <- plotly_build(p)
  # symbol_list = c(
  #   'circle',
  #   'square',
  #   'diamond',
  #   'cross',
  #   'x',
  #   'triangle',
  #   'pentagon',
  #   'hexagram',
  #   'star',
  #   'diamond',
  #   'hourglass',
  #   'bowtie',
  #   'asterisk',
  #   'hash',
  #   'y',
  #   'line'
  # )
  # 
  # for (k in 1:min(nrow(input_df.pca$rotation), length(symbol_list))) {
  #   p$x$data[[k]]$marker$symbol <- symbol_list[k]
  # }
  p
}
```