install.packages("rjson")
install.packages("devtools")
install.packages("plotly")
install.packages("factoextra")
install.packages("tibble")
install.packages("circlize")
install.packages("gplots")
install.packages("heatmaply")
install.packages("plot3D")
install.packages("e1071")
install.packages("ModelMetrics")
install.packages("factoextra")
install.packages("jsonlite")
install.packages("BiocManager")
install.packages("haven")
install.packages("xlsx")
install.packages("DiscriMiner")
install.packages("candisc")

devtools::install_github('vqv/ggbiplot')
devtools::install_github("mixOmicsTeam/mixOmics", force = T)
BiocManager::install("ropls")
